### ISSUE TITLE
爬虫频率和人工复审的问题

### ISSUE THREAD

**Issue by ENDsoft233** [shuosc/shu-course-data#565]
窃以为选课周可以把爬虫频率稍微调高点，如一个小时甚至半个小时一次；

另外人工复审，除了学期变更需要复核，其他情况下窃以为爬虫出问题的概率比较小，可以直接让爬虫去更新到主分支，不需要人工复核。因为如果能爬到学期ID那说明爬虫大概率也没什么问题，人工复核反而会导致前台数据更新较慢。

**Comment by ENDsoft233** [comment]
爬虫频率调高的问题在每年这个选课周都不太一样，要不确定几个特定的月份去提高爬虫频率？

**Comment by chinggg** [comment]
Will take a look at GitHub Actions

**Comment by ENDsoft233** [comment]
https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#onschedule

it allows multi schedules.
